# Session 3

List vs Numpy

In [2]:
import time
import numpy as np

In [ ]:
start = time.time()
n = 1000000
l = []
lst = range(n)

for i in lst:
    l.append(i*2)
print(l)

end = time.time()
print(end-start)


IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



The same when executed as a code, instead of jupyter notebook provides

```sh
[ ..., 1999864, 1999866, 1999868, 1999870, 1999872, 1999874, 1999876, 1999878, 1999880, 1999882, 1999884, 1999886, 1999888, 1999890, 1999892, 1999894, 1999896, 1999898, 1999900, 1999902, 1999904, 1999906, 1999908, 1999910, 1999912, 1999914, 1999916, 1999918, 1999920, 1999922, 1999924, 1999926, 1999928, 1999930, 1999932, 1999934, 1999936, 1999938, 1999940, 1999942, 1999944, 1999946, 1999948, 1999950, 1999952, 1999954, 1999956, 1999958, 1999960, 1999962, 1999964, 1999966, 1999968, 1999970, 1999972, 1999974, 1999976, 1999978, 1999980, 1999982, 1999984, 1999986, 1999988, 1999990, 1999992, 1999994, 1999996, 1999998]
1.2100310325622559
```

In [4]:

# same using numpy
start = time.time()
a=np.array(np.array(n))
print(a*2)
print(a)
end = time.time()
print(end-start)

2000000
1000000
0.0002422332763671875


| Feature | Python List (`list`) | NumPy Array (`ndarray`) |
| :--- | :--- | :--- |
| **Data Types** | Heterogeneous (allows mixed data types like strings and integers together) | Homogeneous (forces all elements to be strictly one data type) |
| **Memory Allocation** | Non-contiguous (stores pointers pointing to scattered memory locations) | Contiguous (stores actual data sequentially in a single memory block) |
| **Performance** | Slower for large datasets due to the overhead of dynamic typing | Exceptionally fast due to C-language backends and CPU cache locality |
| **Size Adjustments**| Dynamic (highly efficient to append or remove elements on the fly) | Fixed (changing the size typically requires generating a brand-new array) |
| **Math Execution** | Requires explicitly writing `for` loops to process multiple items | Supports vectorization (applying operations to entire arrays without loops) |

In [ ]:
# list type - "list"
lst = [1,2,3,4]
print(type(lst))

# array type - "numpy.ndarray" - n dimension array
arr1=np.array(lst)
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


Working with Numpy arrays
- 1 dimensional array

In [8]:
# create zero value array
ar = np.zeros(shape=5)
print(ar, type(ar))

# create 1s
ar1 = np.ones(shape=5)
print(ar1, type(ar1))

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


Create random values in np array

In [9]:
ar = np.random.rand(5)
print(ar, type(ar))

[0.22428082 0.09196022 0.34751303 0.90873769 0.80560587] <class 'numpy.ndarray'>


In [ ]:
# prints the dimension of array
print(ar.ndim)
# prints len of the items in the dimension
print(ar.shape)

1
(5,)


Create random integer value using numpy

In [18]:
arint = np.random.randint(1, 10) # by default gives, size=1, then it returns a type `int`
print(arint)

# if specified size
arint = np.random.randint(1, 10, size=5) # if size is provided, then it return a type `ndarray`
print(arint)
print(arint.shape)
print(arint.ndim)
print(type(arint))

arint = np.random.randint(1, 10, size=1) # by default gives, size=1, then it returns a type `int`
print(arint)
print(type(arint))

3
[7 4 1 9 7]
(5,)
1
<class 'numpy.ndarray'>
[6]
<class 'numpy.ndarray'>


In [30]:
ar = np.array([1,2,3,4,-5,4.0, True])
# since one is a floating point, rest all is converted into float
print(ar)
print(ar.itemsize)

ar = np.array([1,2,"3",4,-5,4.0, True])
# since one is a string, rest all is converted into string
print(ar)
print(ar.itemsize)

# NOTE
ar = np.array([1,2,"3",4,-5,4.0, True,  {"hello": True}])
# since you have an object, the array is treated heterogeneous
# but if you have a list, then it throws an ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (9,) + inhomogeneous part.
print(ar)
print(ar.itemsize)

ar = np.array([1,2,"3",4,-5,4.0, True,  {"hello": True, "numb": [1,2]} ])
print(ar)
print(ar.itemsize)

[ 1.  2.  3.  4. -5.  4.  1.]
8
['1' '2' '3' '4' '-5' '4.0' 'True']
128
[1 2 '3' 4 -5 4.0 True {'hello': True}]
8
[1 2 '3' 4 -5 4.0 True {'hello': True, 'numb': [1, 2]}]
8


Multi dimension array

In [37]:
ar = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("shape:",ar.shape)
print("shape:",ar.shape[1]) # gives columns
print("ndim:",ar.ndim) # give rows
print("size:",ar.size)
print("itemsize:",ar.itemsize)
print("dtype:",ar.dtype)

shape: (2, 5)
shape: 5
ndim: 2
size: 10
itemsize: 8
dtype: int64


Matrix addition

In [38]:
ar1 = np.array([1,2.4, 3, 5])
print(ar1+ar1)

[ 2.   4.8  6.  10. ]


Matrix multiplication

In [ ]:
ar1 = np.array([1,2.4, 3, 5])
print(ar1*2)

[ 2.   4.8  6.  10. ]


Indexing Numpy Array

In [ ]:
ar = np.array([1,2.4,3.4])
lst = [1,2.4,3.4]

if lst[1]==ar[1]:
    print("Same")
else:
    print("different")

True
Same


Idexing Numpy Multidimensional array

In [ ]:
arr = np.array([["a","b","c"], [1,2,3]])
print(arr[1,1])
print(arr[1,2])

2
3


Slicing in numpy
```py
arr[x,y]
```

here,
x - row
y - column (n-1, kind of index)

In [54]:
arr = np.array([["a","b","c"], [1,2,3]])
print(arr[0,:])
print(arr[1,1:])
print(arr[0,:1])

['a' 'b' 'c']
['2' '3']
['a']


In [62]:
arr = np.array([[5,4,3], [1,2,3]])
print("whole array opertion: ",arr>2)
print("selected index",arr[1,:]>2)

whole array opertion:  [[ True  True  True]
 [False False  True]]
selected index [False False  True]


Addition of two array

In [63]:
a = np.array([1,2,3])
b = np.array([2.1,2.5,2.8])

a+b

array([3.1, 4.5, 5.8])

with multi dimension

In [77]:
a = np.array([[1,2], [9,8]])
b = np.array([[2.1,2.8], [6,5]])

print(a+b)

[[ 3.1  4.8]
 [15.  13. ]]


the same goes for the other arithmetic operations

NOTE:
- when you do a*b - it does the element wise multiplication, but
- when you do a.dot(b) - it does matrix multiplication.

In [79]:
print(a*b)

[[ 2.1  5.6]
 [54.  40. ]]


In [78]:
print(b.dot(a))

[[27.3 26.6]
 [51.  52. ]]


in built methods

In [68]:
print("min of a:",a.min())
print("min of b:",b.min())


min of a: 1
min of b: 2.1


SUM : gives a single value, that provides single value
i.e. sum of all elements

In [81]:
ar = np.array([[1,2,3],[4,5,6]])
print(np.sum(ar))

21


Now you can control the sum based on the axis

In [83]:
# row sum -> 0
print(np.sum(ar, axis=0))

# column sum -> 1
print(np.sum(ar, axis=1))

[5 7 9]
[ 6 15]


Now when you have 2D matrix, then using sum, perform addition using `sum` method

In [88]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("using + ",a+b)
print("using sum, axis-0 : ", np.sum((a,b),axis=0))
print("using sum, axis-1 : ", np.sum((a,b),axis=1))

using +  [[ 6  8]
 [10 12]]
using sum, axis-0 :  [[ 6  8]
 [10 12]]
using sum, axis-1 :  [[ 4  6]
 [12 14]]


Concatination:

NOTE:
- Cannot concatenate two diff dimensions

In [101]:
# using 1D array
a = np.array([1,2])
b = np.array([5,6])

print(np.concatenate([a,b]))

[1 2 5 6]


if you try to do, this: then you will get this error:

```py
print(np.concatenate([a,b], axis=1))
```

```bash
AxisError: axis 1 is out of bounds for array of dimension 1
```

In [100]:
# using 2D array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.concatenate([a,b], axis=0)) # by default - row wise
print(np.concatenate([a,b], axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Range

In [112]:
arr = np.arange(8)
abc = np.array(["a","b","c","d","e"])
print(arr)

[0 1 2 3 4 5 6 7]


Split

In [ ]:
print(np.split(arr, [1,3,6]))
print(np.split(abc, [2]))
print(np.split(arr, [3]))

[array([0]), array([1, 2]), array([3, 4, 5]), array([6, 7])]
[array(['a', 'b'], dtype='<U1'), array(['c', 'd', 'e'], dtype='<U1')]
[array([0, 1, 2]), array([3, 4, 5, 6, 7])]


The only difference between these functions is that `array_split` allows indices_or_sections to be an integer that does *not* equally divide the axis. 

For an array of length l that should be split into n sections, it returns `l % n` sub-arrays of size `l//n + 1` and the rest of size `l//n`.


|Function|Handling of Uneven Division|Behavior|
|-|-|-|
|np.split|Strict|Raises a ValueError if the array cannot be divided into equal sized chunks.|
|np.array_split|Flexible|"Does not raise an error. If the division isn't equal, it distributes the ""remainder"" elements into the first few sub-arrays."|

In [108]:
print(np.array_split(arr,3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]
