A class has 8 students and 4 subjects.
1. Generate marks randmly between 40 and 100.
2. Find:
   - Average marks per student
   - Subject-wise highest marks
   - Student who scored highest total
3. Replace all marks below 50 with 0.

Thoughts:
1. 8 students - 8 rows
2. 4 subjects - 4 columns
3. for each subject use np.random.randint for generating marks in given range

In [1]:
# import statements
import numpy as np
np.random.seed()

In [2]:
# generate marks for each student
# i.e. start, stop(excluding), (8 rows, 4 col)
marks = np.random.randint(40, 101, (8,4))
print(marks)

[[ 48  76 100  68]
 [ 85  61  46  52]
 [ 97  59  70  45]
 [ 73  90  86  78]
 [ 54  77  44  63]
 [ 90  64  88  75]
 [ 88  74  73  90]
 [ 50  50  62  60]]


In [ ]:
# Find Avg per student
avg = np.mean(marks, axis=1)
print("Avg: ",avg)

Avg:  [73.   61.   67.75 81.75 59.5  79.25 81.25 55.5 ]


In [ ]:
# Find Highest marks per subject
max = np.max(marks, axis=0)
print("Max: ",max)

Max:  [ 97  90 100  90]


In [ ]:
# Find total per student
total = np.sum([marks], axis=0)
print("Total: ", total)

# Find student who scored highest mark
student_index = np.argmax(total)
print("Student who scored highest mark is at index: ", student_index)
print("Mark of the student: ", marks[student_index])

Total:  [[ 48  76 100  68]
 [ 85  61  46  52]
 [ 97  59  70  45]
 [ 73  90  86  78]
 [ 54  77  44  63]
 [ 90  64  88  75]
 [ 88  74  73  90]
 [ 50  50  62  60]]
Student who scored highest mark is at index:  2
Mark of the student:  [97 59 70 45]


In [6]:
# replace marks < 50 with 0
marks[marks<50] = 0
print("New marks: ", marks)

New marks:  [[  0  76 100  68]
 [ 85  61   0  52]
 [ 97  59  70   0]
 [ 73  90  86  78]
 [ 54  77   0  63]
 [ 90  64  88  75]
 [ 88  74  73  90]
 [ 50  50  62  60]]
