Company has 5 departments and 6 employee each.
1. Generate salary matrix.
2. Find:
   1. Department-wise average salary
   2. Employee-wise maximum salary
3. Increase all salaries by 10%
4. Find total salary expenditure.

Thoughts:
1. 5 department - 5 columns
2. 6 employee - 6 rows
3. for each employee use np.random.randint for generating salary in given range

In [1]:
# import statements
import numpy as np
np.random.seed()

In [2]:
# generate salary for each employee
# i.e. start, stop(excluding), (6 rows, 5 col)
salary = np.random.randint(30000, 1200000, (6,5))
print(salary)

[[1161751  987108  405089 1033711  605587]
 [ 460713  837835  541877  623278  674016]
 [1117054 1113517 1116204  321700 1158258]
 [ 333777 1163976  681339  277862  374131]
 [ 738634   84232  468270 1159693  772121]
 [ 212450  273133  243595  910175  108273]]


In [3]:
# Find Avg per department
avg = np.mean(salary, axis=0)
print("Avg: ",avg)

Avg:  [670729.83333333 743300.16666667 576062.33333333 721069.83333333
 615397.66666667]


In [4]:
# Find employee wise max salary
max = np.max(salary, axis=1)
print("Max: ",max)

Max:  [1161751  837835 1158258 1163976 1159693  910175]


In [5]:
# increase all salaries by 10%
salary=salary+(salary*(10/100))
print("new salary: ", salary)

new salary:  [[1277926.1 1085818.8  445597.9 1137082.1  666145.7]
 [ 506784.3  921618.5  596064.7  685605.8  741417.6]
 [1228759.4 1224868.7 1227824.4  353870.  1274083.8]
 [ 367154.7 1280373.6  749472.9  305648.2  411544.1]
 [ 812497.4   92655.2  515097.  1275662.3  849333.1]
 [ 233695.   300446.3  267954.5 1001192.5  119100.3]]


In [8]:
# total salary
totalByDepartment = np.sum(salary,axis=1)
print(totalByDepartment)

# overallTotal
print("overall salary expenditure: ", np.sum(totalByDepartment))

[4612570.6 3451490.9 5309406.3 3114193.5 3545245.  1922388.6]
overall salary expenditure:  21955294.900000002
